# Generated by Django 5.2.6 on 2025-11-15 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='points',
            new_name='plays',
        ),
        migrations.AddField(
            model_name='profile',
            name='visits',
            field=models.IntegerField(default=0),
        ),
    ]
